import{a as w,S,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const q="51560534-ee0888e2507fe11f794ee77c8";async function p(o,r=1){return(await w("https://pixabay.com/api/",{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".loader-bottom"),g=document.querySelector(".btn-load-more");function y(o){const r=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:a,comments:b,downloads:v})=>`
        <li class="gallery-card">
            <a href="${i}">
            <img src="${s}" alt="${e}" width="360"/></a>
            <div class="descr">
                <p><span>Likes</span> ${t}</p>
                <p><span>Views</span> ${a}</p>
                <p><span>Comments</span> ${b}</p>
                <p><span>Downloads</span> ${v}</p>
            </div>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),L.refresh()}const L=new S(".gallery a",{captionsData:"alt",captionsDelay:250});function M(){f.innerHTML="",L.refresh()}function B(){h.classList.remove("hidden")}function $(){h.classList.add("hidden")}function E(){m.classList.remove("hidden")}function P(){m.classList.add("hidden")}function R(){g.classList.replace("hidden","load-more-active")}function l(){g.classList.replace("load-more-active","hidden")}const C=document.querySelector(".form"),H=document.querySelector("input"),c=document.querySelector(".btn-load-more");let d=1,u="",I=0;C.addEventListener("submit",O);c.addEventListener("click",x);function O(o){o.preventDefault();const r=H.value.toLowerCase().trim();if(!r){n.warning({title:"Warning",message:"Fill in the field!",position:"topRight"});return}B(),M(),l(),u=r,p(u,d).then(s=>{const i=s.hits,e=s.totalHits;if(i.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(i),i*15>=e?(l(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):R()}).catch(s=>{n.error({title:"Error",message:s.message,position:"topRight"})}).finally(()=>{$()})}function x(){d++,E(),c.disabled=!0,p(u,d).then(o=>{y(o.hits),o.hits*15>=I&&(l(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const s=document.querySelector(".gallery-card").getBoundingClientRect().height;window.scrollBy({top:s*2,left:0,behavior:"smooth"})}).catch(o=>{n.error({title:"Error",message:o.message,position:"topRight"})}).finally(()=>{P(),c.disabled=!1})}
//# sourceMappingURL=index.js.map
