import{a as S,S as w,i}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const q="51560534-ee0888e2507fe11f794ee77c8";async function d(r,o=1){return(await S("https://pixabay.com/api/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".btn-load-more");function h(r){const o=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:t,views:a,comments:b,downloads:v})=>`
        <li>
            <a href="${n}">
            <img src="${s}" alt="${e}" width="360"/></a>
            <div class="descr">
                <p><span>Likes</span> ${t}</p>
                <p><span>Views</span> ${a}</p>
                <p><span>Comments</span> ${b}</p>
                <p><span>Downloads</span> ${v}</p>
            </div>
        </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),g.refresh()}const g=new w(".gallery a",{captionsData:"alt",captionsDelay:250});function M(){p.innerHTML="",g.refresh()}function y(){f.classList.remove("hidden")}function L(){f.classList.add("hidden")}function $(){m.classList.replace("hidden","load-more-active")}function l(){m.classList.replace("load-more-active","hidden")}const E=document.querySelector(".form"),P=document.querySelector("input"),I=document.querySelector(".btn-load-more");let c=1,u="",O=0;E.addEventListener("submit",R);I.addEventListener("click",H);function R(r){r.preventDefault();const o=P.value.toLowerCase().trim();if(!o){i.warning({title:"Warning",message:"Fill in the field!",position:"topRight"});return}y(),M(),l(),u=o,d(u,c).then(s=>{const n=s.hits,e=s.totalHits;if(n.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(n),c*15>=e?(l(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$()}).catch(s=>{i.error({title:"Error",message:s.message,position:"topRight"})}).finally(()=>{L()})}function H(){c++,y(),d(u,c).then(r=>{h(r.hits),c*15>=O&&(l(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(r=>{i.error({title:"Error",message:r.message,position:"topRight"})}).finally(()=>{L()})}
//# sourceMappingURL=index.js.map
