import{a as S,S as q,i}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const M="51560534-ee0888e2507fe11f794ee77c8";async function f(s,t=1){return(await S("https://pixabay.com/api/",{params:{key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".loader-bottom"),g=document.querySelector(".btn-load-more"),L=new q(".gallery a",{captionsData:"alt",captionsDelay:250});function b(s){const t=s.map(({webformatURL:r,largeImageURL:a,tags:e,likes:o,views:c,comments:v,downloads:w})=>`
        <li class="gallery-card">
            <a href="${a}">
            <img src="${r}" alt="${e}" width="360"/></a>
            <div class="descr">
                <p><span>Likes</span> ${o}</p>
                <p><span>Views</span> ${c}</p>
                <p><span>Comments</span> ${v}</p>
                <p><span>Downloads</span> ${w}</p>
            </div>
        </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),L.refresh()}function B(){m.innerHTML="",L.refresh()}function $(){h.classList.remove("hidden")}function E(){h.classList.add("hidden")}function P(){y.classList.remove("hidden")}function R(){y.classList.add("hidden")}function I(){g.classList.replace("hidden","load-more-active")}function l(){g.classList.replace("load-more-active","hidden")}const O=document.querySelector(".form"),C=document.querySelector("input"),d=document.querySelector(".btn-load-more");let n=1,u="",p=0;O.addEventListener("submit",H);d.addEventListener("click",x);async function H(s){s.preventDefault();const t=C.value.toLowerCase().trim();if(!t){i.warning({title:"Warning",message:"Fill in the field!",position:"topRight"});return}n=1,$(),B(),l(),u=t;try{const r=await f(u,n),a=r.hits;if(p=r.totalHits,a.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(a),n*15>=p?(l(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):I()}catch(r){i.error({title:"Error",message:r.message,position:"topRight"})}finally{E()}}async function x(){n++,P(),d.disabled=!0;try{const s=await f(u,n);b(s.hits),n*15>=p&&(l(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const t=document.querySelector(".gallery-card");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,left:0,behavior:"smooth"})}}catch(s){i.error({title:"Error",message:s.message,position:"topRight"})}finally{R(),d.disabled=!1}}
//# sourceMappingURL=index.js.map
